FROM justinvanwinkle/dotnet-ide:latest
LABEL maintainer "vanwinkle.justin@gmail.com"

# Download and extract rider
RUN cd /opt && \
    mkdir rider && \
    cd rider && \
    curl -L `echo -n \`curl -s 'https://data.services.jetbrains.com/products/releases?code=RD&latest=true&type=eap' | jq -r '.RD[0].downloads.linux.link'\`` | \
    tar xz
